swagger: '2.0'
info:
  title: Distribution Account Webhooks API
  version: '1.0'
host: global-api-sandbox.lianlianpay-inc.com
basePath: /b2b-import/v1
schemes:
- https
consumes:
- application/json
produces:
- application/json
tags:
- name: Webhooks
paths:
  /webhooks:
    parameters: []
    get:
      summary: Get Webhook Registration List
      tags:
      - Webhooks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/webhook'
              examples:
                Example 1:
                  value:
                    id: '202301014783376'
                    url: https://global-api-sandbox.lianlianpay-inc.com
                    topic: outbound.funding.funded
                    createTime: '2023-01-01T10:15:22Z'
      operationId: get-webhook-registration-list
      description: 'Get a list of webhook registrations of a client. If no registrations, empty list will be returned.


        Return type is List<`Webhook`>'
      x-stoplight:
        id: 6kew4nuburweb
    post:
      summary: Register Webhook
      operationId: post-webhooks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/webhook'
              examples:
                Example 1:
                  value:
                    id: '202301014783376'
                    url: https://global-api-sandbox.lianlianpay-inc.com
                    topic: outbound.funding.funded
                    createTime: '2023-01-01T10:15:22Z'
        '400':
          description: 'Bad Request

            Possible error codes:


            | Code | Description |

            |------|-------------|

            | 999995 | \[PARAMETER\] ERROR_MESSAGE |

            | 108012 | Duplicate Webhook Registration |'
          content:
            application/json:
              schema:
                type: object
                description: Failed object in LianLian Global's system
                properties:
                  code:
                    type: string
                    x-stoplight:
                      id: kzoo21dzzomta
                  message:
                    type: string
                    x-stoplight:
                      id: op9s7jvj4eopi
                  httpCode:
                    type: string
                    x-stoplight:
                      id: 3eolof69kmysd
                required:
                - code
                - message
                - httpCode
            application/xml:
              schema:
                type: object
                properties: {}
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                description: Error object in LianLian Global's system
                properties:
                  code:
                    type: string
                    x-stoplight:
                      id: u288z82c8r38j
                  message:
                    type: string
                    x-stoplight:
                      id: txki5g6jb84mz
                  httpCode:
                    type: string
                    x-stoplight:
                      id: bcuxogfz6vnh7
                required:
                - code
                - message
                - httpCode
              examples:
                Example 1:
                  value:
                    code: '500000'
                    message: Internal Server Error, Contact LianLian Global for technical support
                    httpCode: '500'
      x-stoplight:
        id: 90mva0enqzi93
      description: '*Register a webhook in LianLian Global''s system. Registered webhook will be used to send events generated by LianLian Global''s system.*<br>在连连国际系统中注册一个webhook。已注册的webhook将用于发送由连连国际系统生成的事件。


        Return type is `Webhook` object.'
      parameters:
      - schema:
          type: string
        in: header
        name: Idempotency-Key
        description: '**Optional**A unique value generated by the client which the server uses to recognize subsequent retries of the same request.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  x-stoplight:
                    id: kznmvvdef1cl9
                  maxLength: 64
                  description: Webhook callback url
                topic:
                  type: string
                  x-stoplight:
                    id: koy96fsby537p
                  description: "Event topics defined in LianLian Global's system.\r\n\r\n| Topic | Description |\r\n|--------|------------|\r\n| outbound.payer.approved |  payer approved |\r\n| outbound.payer.rejected  |  payer reject |"
              required:
              - url
              - topic
        description: ''
      tags:
      - Webhooks
  /webhooks/{webhookId}:
    parameters:
    - schema:
        type: string
      name: webhookId
      in: path
      required: true
    get:
      summary: Get Webhook Registration
      operationId: get-webhooks-webhookId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/webhook'
              examples:
                Example 1:
                  value:
                    id: '202301014783376'
                    url: https://global-api-sandbox.lianlianpay-inc.com
                    topic: outbound.funding.funded
                    createTime: '2023-01-01T10:15:22Z'
      x-stoplight:
        id: 8zd5naoj2nce2
      description: '*Get a webhook registration details by `webhookId`.*


        Return type is `Webhook` object'
      tags:
      - Webhooks
    delete:
      summary: Delete Webhook Registration
      operationId: delete-webhooks-webhookId
      responses:
        '200':
          description: OK
      x-stoplight:
        id: 1gk3vftkvxe8v
      description: '*Delete a webhook registration by `webhookId`.*'
      tags:
      - Webhooks
components:
  schemas:
    webhook:
      title: Webhook
      type: object
      description: 'Object used in LianLian Global''s system to describe the client registration of event callbacks.<br>

        对象，用于描述事件回调的客户端注册。<br>

        LianLian Global uses this object to identify events which should be pushed back to client''s url.<br>

        连连国际使用这个对象来识别应该推回到客户端url的事件。'
      examples:
      - id: '202301014783376'
        url: https://global-api-sandbox.lianlianpay-inc.com
        topic: outbound.funding.funded
        createTime: '2023-01-01T10:15:22Z'
      x-stoplight:
        id: g54gw9kbk86e5
      properties:
        id:
          type: string
          description: Webhook registration id in LianLian Global's system
          x-stoplight:
            id: qwdp1ope8k27l
          maxLength: 32
        url:
          type: string
          x-stoplight:
            id: zn7ihzytz18s1
          description: Client webhook url
          maxLength: 64
        topic:
          type: string
          x-stoplight:
            id: 5g9j9zgbb5xjm
          description: "Event topics defined in LianLian Global's system.\r\n\r\n| Topic | Description |\r\n|--------|------------|\r\n| OUTWARD_PAYERINFO_RESPONSE |  Payer KYC result notification |\r\n| OUTWARD_TRADEFILE_RESPONSE  |  Trade file audit result notification |\r\n| OUTWARD_ORDER_RESPONSE  |  Transaction processing result notification |"
        createTime:
          type: string
          format: date-time
          description: Webhook registration time, UTC+0 timestamp
          x-stoplight:
            id: eba0udmswhw2t
      required:
      - id
      - url
      - topic
      - createTime
